import Navigation from './components/Navigation';

import '../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <head>
        <title>SHM</title>
      </head>
      <body className="flex flex-col h-full">
        <Navigation />
        <div className="flex flex-col p-5 h-full">{children}</div>
      </body>
    </html>
  );
}
