
import Navigation from './components/Navigation'

import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <head>
        <title>SHM</title>
      </head>
      <body>
      <Navigation />
      <div className='p-5'>
      {children}
      </div>
        </body>
    </html>
  )
}
